### ISSUE TITLE
DCM schema?

### ISSUE THREAD

**Issue by rout39574** [ibm-datapower/datapower-configuration-manager#119]
I'm trying to figure out where 

  xmlns:dcm="urn:datapower:configuration:manager"

is defined.     The only xsds in the distro are in the tests-deploy.ant/wsdls_xsds directory, and I don't think they apply to documents of application urn:datapower:configuration:manager

**Comment by rout39574** [comment]
Gee, that didn't end with a call to action. :)  

Please check in the schema or DTD you use to validate dcm documents?

**Comment by richgroot** [comment]
It is just a made-up name, since it names a namespace.  These values used
to be URLs, such as https://something.w3c.org, but then they were
generalized.

Hope that helps,
Rich

**Comment by rout39574** [comment]
I'm failing to communicate, sorry.

The XML documents we edit to drive DCM, such as 

    <dcm:definition xmlns:dcm="urn:datapower:configuration:manager">
    <dcm:upload environment="test" local="yadda" remotedir="config:///" />
    <dcm:object-create environment="test">  </dcm:object-create>
    </dcm:definition>

That document type is formalized somewhere, right?  So we know, for example, that a dcm:definition might have dcm:upload and dcm:object-create elements, but an element dcm:carrots-have-ears is incorrect, and nothing from the purple-dinousar namespace at all.   So we can validate the form of dcm:definitions, without actually running code.


Either a Document Type Definition, or a schema, is rattling around _somewhere_.     That's what I'm looking for.

**Comment by richgroot** [comment]
Ah! Sorry - no, I didn't ever write a schema for it.  Initially the XML was
evolving and a schema would have been a boat anchor.  Later, well, I didn't
have a good tool for writing schemas.  I still don't.

Thanks,
Rich

**Comment by rout39574** [comment]
Ah.      

How would you describe the relationship between DCM and IBM?    It's certainly not a "supported product";  is it "a set of practices that IBM support understands and recommends" ?   Or is it a fairly conventional open-source "It scratches my itches, use it if you like, good luck!"..    The presence of the codebase in a project more or less acknowledged by IBM fuzzes the lines somewhat. 

Do you consider DCM capable of managing the entire lifecycle of DataPower appliances?

You're delightfully responsive here,  but I have a sense that @richgroot  is not operating ex officio IBM.   So I don't want to abuse that, but  I want to figure out the right intellectual posture for our interaction. :) 

As for schemas; I won't attempt to convert you immediately, but I encourage you to consider them rails to lean on, rather than anchors.  They offer both formal analysis properties, and an obvious place to hang documentation of whatever it was you were thinking.    Holy crow they accelerate communication. 

Would you tolerate schemas as a contribution?

**Comment by richgroot** [comment]
Allen,

I worked extensively with DataPower when I was an IBM DataPower
consultant.  I wrote DCM to help solve the configuration management
problem.  A similar package is DPBuddy, though I have no knowledge how well
they are supported these days.  Basically DCM is a relatively thin wrapper
around the configuration management API.

What follows is based on my own (potentially flawed) understanding, though
conversations that I've had with DP developers confirmed my thoughts.  I
don't speak for IBM!

The core of DP is a massive process, written in C, that implements all the
basic functionality that you see.  Connections, data handling, XSL
compilation, XML processing, all that.  The CLI is a single-threaded
mechanism that manages all the in-memory data structures that control that
behavior of the main process.  This architecture is why there are two
different levels of saving configuration - the first is when you press OK
and behind the scenes a CLI command is run to make the change in-memory,
then later you persist those changes by pressing the save button in the
upper right corner, which performs a "write mem" command behind the
scenes.  (Oh, and since the main process is multi-threaded, following all
those carefully maintained data structures, the CLI must lock those data
structures in order to keep from crashing the system.  That can affect
performance enough that you can't afford to make some kinds of changes
without quiescing a DP.)

The earliest DP software was built to resemble a Cisco router, which is
also command line based.  They quickly decided to add a browser-based UI to
improve marketability.  The architecture they settled on was, essentially,
an XML-based representation of the CLI.  The dp-aux mechanism is a set of
stylesheets that translate SOMA requests to CLI commands.  You can see this
if you set up an XSL step with XML input and text output, then pass it a
domain configuration file.

(I'm going somewhere, dragging you through all these details.)

The UI passes SOMA commands to port 9090 in order to effect changes or
fetch information, just as DCM passes SOMA commands to port 5550.  Each
request is translated to a CLI command that is executed and the result
captured and returned to the UI.  The same underlying code supports both
port 5550 and port 9090, enforcing different, appropriate authentication
schemes.

An important consequence of this architecture is that randomly changing the
SOMA definition will break the UI, so DP developers are generally careful
to avoid SOMA changes that break existing code.  Adding elements,
attributes, and values is much preferred to changing anything that already
works.  If you diff the xml-mgmt files from version to version you will see
that new things tend to be added, few things are ever removed (though that
does happen).  Similarly, if you study the CLI, you'll see new things
added, usually as optional parameters, rather than removing parameters.

DCM is built with all this in mind, which is why I've dragged you through
these details.  There is one more aspect that is both interesting and
useful.  A large part of building a version of DP for testing or release is
a large set of files that define the command line syntax, SOMA, the browser
UI, and some other components.  These are then used to generate the
xml-mgmt schema, the HTML and whatnot for the UI, the CLI interpreter, and
the code that captures the CLI output and returns it in SOMA responses.
That's why DCM doesn't check for classes of errors that basically can't
happen, such as a mismatch between the schema and the CLI syntax.  DCM
doesn't verify all the elements and parameters by design since duplicating
the functionality in dp-aux and the CLI interpreter, which change with
every release, is a massive and mostly pointless undertaking.

Maintaining DCM is mostly about adding support for new features, including
new bits attached to existing commands.  When I was actively maintaining
DCM I'd diff the xml-mgmt files between the current and new versions and
then make appropriate changes to DCM.  It is a bit tedious but not very
difficult.

DCM is open source, and a number of companies used it.  I helped roll it
into UrbanCode, since that team had been tasked with adding DP support.
The UrbanCode team supports DCM in terms of difficulties with UrbanCode,
but I don't know that they have time or energy to maintain DCM across DP
versions.

I didn't do a schema in the beginning because things were changing so
rapidly, evolving the schema would have been a drag on my time and effort.
Once things stabilized, I just had too many other things to do.  It's a
good idea, just not one I've had the time or tools to pursue.

Contributions from the community are welcome, including updating DCM to
match past and current versions of the SOMA schema.  I haven't been active
in DCM maintenance since I left IBM several years ago but I'd be glad to
advise you if you had any additional questions (richgroot@gmail.com).

Thanks,
Rich

**Comment by rout39574** [comment]
Thanks for your detailed explanation, and the background of where DCM came from.   I'll experiment with schemata for the DCM application in particular; I agree that trying to apply them to delivered API payloads is probably a waste of time.   if I come up with something I think might be useful, I'll submit a PR for discussion.
