### ISSUE TITLE
Request: plugin step for "reset domain" feature

### ISSUE THREAD

**Issue by tomashudec** [ibm-datapower/datapower-configuration-manager#13]
It would be great to have plugin step for "reset domain" functionality in UCD-DataPower plugin.

**Comment by richgroot** [comment]
It has been a while since you made this suggestion.  Do you still like the idea?  I've thought that domain reset was incomplete because while it resets the objects in the domain back to those that are present in a fresh domain but it does NOT reset files.  As a result I delete and recreate the domain when I want a pristine domain.
