### ISSUE TITLE
unimportConfig - dead?

### ISSUE THREAD

**Issue by tbro028** [ibm-datapower/datapower-configuration-manager#20]
The xsl files unimport-extract-disable.xsl are not present. Assuming this is either incomplete, or no longer intended to be used so some comments should be made in the task-defs file.

**Comment by nhmathis** [comment]
Hi,

I believe your concerns are coming from here: https://github.com/ibm-datapower/datapower-configuration-manager/blob/881cc35a659c17ec83fe2e76b72ae4bde9c08506/src/dcm-taskdefs.ant.xml#L3466

This code has existed since the original commit in 2014. I suspect this snippet was pulled from internal DataPower somewhere with the intent of saving it for potential future use. The macrodef `unimportConfig` is not used anywhere, so I am not concerned with it created bugs or problems with the present code. For the time being, I am going to let it be unless it causes a problem. 

I have made a note of it in a recent commit. 

-Nick

**Comment by richgroot** [comment]
Unimport was intended as "undo" for an import operation, giving you the
ability to remove a service from a domain.  I haven't actually used it in
the real world, though, and I don't know that anyone else has used it, so I
wouldn't suggest using it unless you are prepared to be a pioneer.

**Comment by nhmathis** [comment]
I can see this command having value in the context of UCD if a deployment goes awry following an import step. This is a quick method to revert back to an earlier state, however you would then have incorrect versioning inventory. Typically UCD users would use a snapshot system to revert back to a success state. This option is far more safe.
