### ISSUE TITLE
how to create FSH

### ISSUE THREAD

**Issue by ealdwairi** [ibm-datapower/datapower-configuration-manager#3]
Hello,

I just starting using DCM, and I am very happy with it so far. 
one question, how can I create FSH using command line? I couldn't find a  task to do so?!

thank you

**Comment by richgroot** [comment]
The easiest way is to create an FSH using the DP web browser and then export it in a .zip file.  Then you can use this as a "template", importing it into domains as needed.  You'll probably want to make adjustments to the imported object using either deployment policy elements (see dcm:deployment-policy) during the import operation or make changes by using the object-from-def and dcm:object-* elements following the import.

**Comment by ealdwairi** [comment]
Thank you Rich for your quick reply. I am so in happy with DCM so far,
amazing how easy deployment of DP is with it.

I have one question, is there an easy way to create the policy xml file? as
of now, I literally examine export.xml of the package to be imported, then
I manually create policy deployment xml file.
so far I am playing with the tool, so creating such file no big deal,
however this is going to be challenging when we start using the tool for
our real services, export file is huge, so many values to be alerted from
env to env.
thank you and have a great day Rich.

On Tue, Feb 3, 2015 at 7:43 PM, Rich Groot <notifications@github.com> wrote:

> The easiest way is to create an FSH using the DP web browser and then
> export it in a .zip file. Then you can use this as a "template", importing
> it into domains as needed. You'll probably want to make adjustments to the
> imported object using either deployment policy elements (see
> dcm:deployment-policy) during the import operation or make changes by using
> the object-from-def and dcm:object-* elements following the import.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ibm-datapower/datapower-configuration-manager/issues/3#issuecomment-72768338>
> .
>



-- 


Regards,
Eklas

**Comment by vinodmarisarla** [comment]
Hello Rich,
I am very happy with this tool , but i am getting a java error while inporting an object into a domain.Can you please give me a resolution. i have attached the error i am getting.
![capture](https://cloud.githubusercontent.com/assets/12851393/9341765/d6700fc6-45c5-11e5-9a4e-31894edc2187.PNG)

Thanks,
Vinod.

**Comment by richgroot** [comment]
Vinod,

Sorry you are having trouble.  That error indicates that it can't find
Xalan, which is part of the dcm.nnn.jar file.

I just set up a clean Linux virtual machine, installed OpenSDK 1.8 (Java)
and ant 1.9.6 from the apache website, built DCM from scratch, and
successfully ran an upload-from-def test.  This leads me to think that
there may be a problem with your particular environment rather than with
DCM itself, so perhaps you can check some things.

By the way, the upload-from-def test that I ran from the dcm/dcm directory:

    ant -f deploy.ant.xml -Ddcm.dir=. -Dhost=192.168.13.15 -Ddomain=default
-Duid=admin -Dpwd=*******
-Dupload.file=/home/regroot/dcm/dcm/tests-deploy.ant/upload-01.dcm.xml
upload-from-def

You might ensure that you have a complete and correct build:

1. Ensure that you have the latest DCM code from the website.
2. Delete the lib directory so that you download the latest ant and xalan
jar files during the build process.
3. ant clean distro
4. dist/dcm.1.jar should be about 3.1 MB.

At this point you should be able to successfully run the test that I
mentioned above.

If any of this fails then please send me the console output of the "ant
clean distro" and I'll see if I can help you a bit more.

Thanks,
Rich
