### ISSUE TITLE
how to create a definition file

### ISSUE THREAD

**Issue by ealdwairi** [ibm-datapower/datapower-configuration-manager#4]
Hi Folks,

I  need more help :( I am not  a programmer, so I am facing a lot of challenges to build my own code.
for example, if you follow the easyStart project, you can see that the author created load-balancer-group-to-ant.xml to create/update loadbalancer group. for that there were two important files specifically  to this task:
1-load-balancer-group-to-ant.xml ( complicated)
2-ucdDemo.lbg.dcm.xml (easy after we have 1 built)

my question is I want to do the same for HTTPSSourceProtocolHandler to create/update it during deployment and many other objects . I tried to manually build HTTPS-SourceProtocol-Handler-to-ant.xml file by looking at xml-mgmt.xsd ..it's so time consuming process and complicated. 

how can I do that? is there an easy way to figure out the definition dm for any datapower object?

**Comment by richgroot** [comment]
Sorry for the long delay in responding.  The problem is that the only real way to know what to change is to unzip the exported .zip file and then study the export.xml file.  I tried to make the definition file format straightforward, especially for load balancer groups, valcreds, and idcreds.  Deployment policies, which make changes during the import process, and object-create/modify unavoidably require some detailed knowledge of the structure of the various DataPower objects.  I'd like to add a UI someday for working with definition files but that is somewhat in the future, at best.

Can you provide some specific kinds of changes that you need to accomplish?

**Comment by moraesf** [comment]
@ealdwairi Any updates you can provide us?

**Comment by ealdwairi** [comment]
thanks for the follow up Rick. while I was searching on the subject, I ran
across JAXB. so I started my own project on datapower deployment and of
course using many of the classes which are provided by DCM. I started by
converting datapower object xsd into java classes, then from there there
are unlimited way to do deployment. I will share my code and ideas once I
am done.

On Thu, Mar 26, 2015 at 9:22 AM, Rich Groot <notifications@github.com>
wrote:

> Sorry for the long delay in responding. The problem is that the only real
> way to know what to change is to unzip the exported .zip file and then
> study the export.xml file. I tried to make the definition file format
> straightforward, especially for load balancer groups, valcreds, and
> idcreds. Deployment policies, which make changes during the import process,
> and object-create/modify unavoidably require some detailed knowledge of the
> structure of the various DataPower objects. I'd like to add a UI someday
> for working with definition files but that is somewhat in the future, at
> best.
>
> Can you provide some specific kinds of changes that you need to accomplish?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ibm-datapower/datapower-configuration-manager/issues/4#issuecomment-86511415>
> .
>



-- 


Regards,
Eklas
