### ISSUE TITLE
Allow Quiesce/Unquiesce of multiple domains

### ISSUE THREAD

**Issue by willeje** [ibm-datapower/datapower-configuration-manager#42]
Hi,

Knowing that UCD doesn't support for-each loops it would be nice to have the DataPower plugin to provide the option to  Quiesce/Unquiesce multiple domains in one step.

Functionality would be simular to the backupdomains step.

Thanks,
Jeroen

**Comment by nhmathis** [comment]
Hi,

In the context of UCD and DataPower this request does not make sense and can be handled in a different manner. As you have identified, UCD does not allow loops as we think of them in coding. Because we generally believe one component should map one tool-object, we handle a multi-request in a different way. 

Ideally, we suggest mapping one DataPower domain to one UCD component. This means, all component processes are applied to a single component/domain. Therefore, multiple domain [un]quiesces can occur through an Application Process and then the use of the `Install Multiple Components` step. 

If configured correctly, this step can run a "Unquiesce/Quiesce" component process against each tagged component. In this sense, it would be looping through all domains and running the quiesce command as you requested.

-Nick
