### ISSUE TITLE
Deployment Policy Variables

### ISSUE THREAD

**Issue by willeje** [ibm-datapower/datapower-configuration-manager#45]
Hi,
I'm using the DataPower UCD plugin and wondered if it is it currently possible to use "Deployment Policy Variables" together with the "Import (Deployment Policy Object)" step?

If not, is it somewhere on the roadmap?

Thanks,
Jeroen

**Comment by nhmathis** [comment]
Hi @willeje,

Using the DCM Definifion File ([docs](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/dcm:deployment-policy-element)), you should be able to specify Deployment Policy Variables as element values. However, as it must pass through UCD and DCM before it gets to the SOMA calls, you may need to escape some characters. 

Unfortunately, if this feature does not exist, then work must be done to the DCM client before the plugin. Because the DCM client is supported on a best effort basis, we cannot guarantee a timeline of when the feature would be supported. You or your colleagues are welcome to submit a pull request with the necessary changes if you happen to write a working implementation.

-Nick

**Comment by peteles** [comment]
Hello, I've implemented it. What do I do? Branch and a pull request?

Thanks.
