### ISSUE TITLE
Any documentation\help on running DCM tests

### ISSUE THREAD

**Issue by edHowardDev** [ibm-datapower/datapower-configuration-manager#48]
Hi there

I am keen to use DCM in our enterprise environment.
I am working on testing selected ant target that we may use.

Is there any more updated documentation other WIKI?
Particularly, it is ok to run test-deploy.ant and test-wdp. Do i just need a test domain?

**Comment by nhmathis** [comment]
The `test-deploy.ant`  files were used when the DCM was first in development to test it's commands. Since then, targets have been certified by many users. Feel free to run the tests in your own deployments, but they likely won't satisfy a personal use case. The tests can be run against any domain, but we recommend a sandbox environment!

I would suggest walking through [Easy On Ramp](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Easy-On-Ramp) and [Quick Start](https://github.com/ibm-datapower/datapower-configuration-manager/wiki/Quick-Start) documentation. Once you understand how to run a simple ant command, you can find all of the other possibilities in the [deploy.ant.xml](https://github.com/ibm-datapower/datapower-configuration-manager/blob/2a2a2b81e455afd1768f5ee6b0464ecd58dd6f6b/deploy.ant.xml) file. If it's your first time running Ant commands, there is plenty of Ant specific documentation throughout the internet. 

If you are looking to eventually run the UCD plugin, we have a bunch of good resources on the [plugin's usage page](https://developer.ibm.com/urbancode/plugindoc/ibmucd/ibm-datapower-configuration-manager/1-2/usage/).
