### ISSUE TITLE
Import not changing files

### ISSUE THREAD

**Issue by neoiet2009** [ibm-datapower/datapower-configuration-manager#57]
hi guys,

I am using dcm to deploy zip. The issue arise when I change some file content and upload the same in git repository. And execute DCM job.Any change in file is not getting inported in DP...

From Hermann, I got to know there might be issue when I create zip not on DP..it might be not updating checksum. Do wo have any job to build DP export from GIT.

**Comment by nhmathis** [comment]
This is a known issue with the DCM Ant CLI. The `<blacklist>` does not effectively exclude files. If using a UrbanCode Deploy, the attached Process template json file provides a work around that identifies the files within the .zip, removes them, and creates a new zip with the files removes. 

[DataPower+Blacklist+Example.txt](https://github.com/ibm-datapower/datapower-configuration-manager/files/1103131/DataPower.Blacklist.Example.txt)

Note: GitHub does not allow me to upload .json files. You'll need to rename the extension.

**Comment by borislopezaraoz** [comment]
Hello, is someone working on a fix? @nhmathis can you provide more info or some pointers, where should I start if I want to fix this?

**Comment by richgroot** [comment]
I believe the problem is not with DCM but is rather in the underlying
deployment policy mechanism on DataPower, which is capable only of
affecting the objects that are imported, not files.   The design of
deployment policies has always been a little unsatisfactory to me (I argued
for a more open approach). Still, done is done.

I avoid these limitations by keeping my files separate from the .zip and
uploading them in a separate step.  This allows me to keep all the files
under individual source control, and also fine control of which files are
uploaded, and to where.

Hope this helps,
Rich

**Comment by borislopezaraoz** [comment]
OK, I am using task upload-dir and it is working well
Thanks @richgroot !
