### ISSUE TITLE
Deployment Policy Definitions [Need Help]

### ISSUE THREAD

**Issue by bmarur** [ibm-datapower/datapower-configuration-manager#65]
Hello Experts,

I'm working with DCM project to automate our deployments, As part of it, I'm working with Import-with-Def ANT target to import a service package with deployment policy. I was able to  Modify Property through  definitions file, I would like to filter out certain configuration items in the import package through Deployment policy definitions, I was trying out "delete-property" element in the deployment definition but, that isn't doing what I desire.

PFB property elements

```
<delete-property prop-name="Cryptocert_15" type="Certificate" name="valCred-CCS"/>
<delete-property prop-name="Cryptocert_16" type="Certificate" name="valCred-CCS"/>
<delete-property prop-name="Cryptocert_17" type="Certificate" name="valCred-CCS"/>
<delete-property prop-name="Cryptocert_18" type="Certificate" name="valCred-CCS"/>
<delete-property prop-name="Cryptocert_19" type="Certificate" name="valCred-CCS"/>
<delete-property prop-name="Cryptocert_20" type="Certificate" name="valCred-CCS"/>
```

PFA validation credential snapshot

![import_with_def_no_objects_deleted](https://user-images.githubusercontent.com/28853701/28242625-9a158162-697e-11e7-8295-9dfb9df69b44.PNG)

Please let me know what should be correct definition parameter in order filter out certificate entries in Validation credential object.

Thanks,
Bharath

**Comment by nhmathis** [comment]
The DCM offers many ways to tackle this issue. I've tried to outline a few examples that may help this issue along with others.

It's first important to understand the relationship where the Cryptocerts are also properties on the valCred-CCS object. This means a simple delete or blacklist of the Cryptocerts will leave a hollow-object on the valCred-CCS. In this case, there will still be remnants of the Cryptocerts on the DataPower domain. Therefore, we must manage the valCred-CCS object as well. 

In Example 1, the definitions file will prevent the Cryptocert's objects export.xml definitions from importing, but because they are still referenced, they will be empty, or hollow, CryptoCertificate properties on the valCred-CCS object.

Example 1:
<dcm:definition xmlns:dcm="urn:datapower:configuration:manager">

<dcm:deployment-policy>


<black-list name="Cryptocert_15"/>
<black-list name="Cryptocert_16"/>
<black-list name="Cryptocert_17"/>
<black-list name="Cryptocert_18"/>
<black-list name="Cryptocert_19"/>
<black-list name="Cryptocert_20"/>

</dcm:deployment-policy>
</dcm:definition>


To completely prevent the import of these CryptoCertificate objects, I had to remove all certificate references from the valCred-CCS. Unfortunately, the dcm tool does not have a method of removing a single Certificate property from the valcred object. It's all or nothing command.

Example 2 will remove all Certificate properties from the valCred-CCS object through the <delete-property> element. Then, combined with the blacklisting, Cryptocert_15-20 objects will not be imported. However, while CryptoCert_1-14 will still exist in the DataPower domain, they will not be mapped to the valCred-CCS object.

Example 2:
<dcm:definition xmlns:dcm="urn:datapower:configuration:manager">

<dcm:deployment-policy>


<delete-property prop-name="Certificate" name="valCred-CCS" />


<black-list name="Cryptocert_15"/>
<black-list name="Cryptocert_16"/>
<black-list name="Cryptocert_17"/>
<black-list name="Cryptocert_18"/>
<black-list name="Cryptocert_19"/>
<black-list name="Cryptocert_20"/>

</dcm:deployment-policy>
</dcm:definition>

Now that we have un-mapped all Certificate properties and deleted the Cryptocert_15-20s, in example 3, we will add Cryptocert_1-14 back one-by-one. We'll do that through the add-property element. 

Example 3:
dcm:definition xmlns:dcm="urn:datapower:configuration:manager">

<dcm:deployment-policy>


<delete-property prop-name="Certificate" name="valCred-CCS" />


<black-list name="Cryptocert_15"/>
<black-list name="Cryptocert_16"/>
<black-list name="Cryptocert_17"/>
<black-list name="Cryptocert_18"/>
<black-list name="Cryptocert_19"/>
<black-list name="Cryptocert_20"/>


<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_1" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_2" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_3" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_4" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_5" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_6" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_7" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_8" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_9" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_10" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_11" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_12" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_13" name="valCred-CCS" />
<add-property new-prop-name="Certificate" new-prop-value="Cryptocert_14" name="valCred-CCS" />

</dcm:deployment-policy>

</dcm:definition>

At this point, using the Import (Definition) step, the valCred-CCS object should be back to its original state minus the Cryptocert_15-20s. 

Another possible approach would be to remove the entire valCred-CCS object. With this object deleted, there would no longer be any hollow Cryptocert objects. Then, the object could be re-imported with the Cryptocerts 15-20 blacklisted.
