### ISSUE TITLE
If a specified a domain does not exist to restart or deleteDomain, command should fail.

### ISSUE THREAD

**Issue by bastump** [ibm-datapower/datapower-configuration-manager#93]
What happens now:

domain-restart:
     [echo] Did not restart domain ${domain} on ${host} since it does not exist.

BUILD SUCCESSFUL

**Comment by richgroot** [comment]
Brian,

Yes, that is the expected behavior, though I admit it may not be the
desired behavior. If you browse through the various domain-related tasks
you'll see that several of them explicitly skip taking the intended action
(e.g. restarting or deleting a domain) when that domain does not exist.  In
hindsight it was probably the wrong design decision, but at that point the
ignore-errors flag did not exist so I opted for the behavior that you now
see.

The original thinking was that users would always create the target domain
as part of their flow, which has no effect when the domain already exists,
because the code related to domains tries to always fail gracefully.  See
previous paragraph. ;-)

Thanks,
Rich

**Comment by bastump** [comment]
Thanks for the response Rich.  Would it be appropriate to add the ignore-error flags and handle the case properly in a new version?

**Comment by richgroot** [comment]
Brian,

I thought about this a bit and I'm a little concerned about preserving
backward-compatibility.  The proposed approach isn't quite the inverse of
the behavior that exists right now.  For example, currently, a bad uid/pwd
or hostname will stop restartDomain, but ignore-errors=true will skip that
error and plow right on through, meaning that the next operation can't rely
on the previous operation having succeeded, which is a principle that DCM
tries to follow.

Alternatively, we could make up new versions of restartDomain et al. that
insist on preconditions being met, and surface those in the plugin, which
may contribute to making the plugin more confusing to use.  Another
possibility is to add a plugin step and underlying DCM code to insist that
the domain exists (or doesn't) or take the error path in UCD.  A third
alternative is to simply create a new "unforgiving domain action" plugin
step and DCM plumbing that is capable of create, delete, restart, etc.,
while implementing a policy of taking the UCD error path when any
precondition is not met.  That also has the potential to make the plugin
more confusing, again because there are two ways to take the same action on
a domain.

I wonder whether UCD supports more than a success/error branching at each
plugin step?  One possibility is to create a generalized plugin step that
can check for whether a DP object exists, or has some particular bit of
state (up/down, enabled/disabled, value=alice|bob) and then UCD can take
one of several branches, sort of like a switch statement?

Needs some more thought and discussion, I think.

Thanks,
Rich

**Comment by bastump** [comment]
Thanks again for your response Rich.  

I think an additional step to simply detect the existence of domains is the most reasonable solution.  With that approach, the user can build their intended workflow and catch the missing domain without having to create the domain within their process, and it refrains from making duplicate or confusing functionality in the plugin.  

Brian

**Comment by bastump** [comment]
Resolving this issue as we found a very simple solution around it.  

Reading the output log with a post-processing script can allow the step to fail if the domain does not exist.  Here is the sample output log:

```
var exit = properties.get('exitCode');

scanner.register("does not exist", function(lineNumber, line) {
     exit =1 ;
});
scanner.scan();

if (exit == 0) {
    properties.put('Status', 'Success');
}
else {
     properties.put('Status', 'Failure');
}

```
